"""create membership table

Revision ID: 535cc9cbdd98
Revises: 11ac00c5cba7
Create Date: 2026-06-08 20:11:31.102570

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "535cc9cbdd98"
down_revision: str | Sequence[str] | None = "11ac00c5cba7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "membership",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("membership", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_membership_person_id"), ["person_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("membership", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_membership_person_id"))

    op.drop_table("membership")
    # ### end Alembic commands ###
